# Generated by Django 4.1.4 on 2022-12-22 12:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=64, verbose_name='firstname')),
                ('last_name', models.CharField(max_length=64, verbose_name='lastname')),
                ('username', models.CharField(default='<django.db.models.fields.CharField><django.db.models.fields.CharField>', max_length=64, verbose_name='name')),
                ('user_email', models.EmailField(max_length=256, unique=True, verbose_name='email')),
            ],
        ),
    ]
