# Generated by Django 4.1.4 on 2023-01-12 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Edited'),
        ),
    ]
