# Generated by Django 4.1.4 on 2023-02-10 18:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customuser_id_alter_customuser_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='uuid',
        ),
        migrations.AddField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
