# Generated by Django 4.1.4 on 2023-01-12 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_updated_alter_project_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='repo_link',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
