# Generated by Django 4.1.4 on 2023-01-12 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0009_remove_project_created_remove_project_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todotask',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
